dags:
  gitSync:
    enabled: true
    repo: "https://github.com/Kh-1976/airflow-dags.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    period: "1m"
    subPath: ""
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  postgresUser: airflow
  postgresPassword: airflow
  postgresDatabase: airflow
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 8Gi
  service:
    port: 5432
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m" 

airflow:
  migrateDatabaseJob:
    enabled: true
  createUserJob:
    enabled: true
  config:
    CORE__DAGS_FOLDER: '/opt/airflow/dags/repo'

# ✅ ИНИТКОНТЕЙНЕРЫ — работают ВЕЗДЕ без схемы!
scheduler:
  initContainers:
    - name: install-python-packages
      image: apache/airflow:3.1.7-python3.11  # ваша версия
      command: ["/bin/bash", "-c"]
      args:
        - |
          pip install --no-cache-dir confluent-kafka==2.5.0 &&
          chown -R airflow:0 /usr/local/airflow/.local
      volumeMounts:
        - name: pip-cache
          mountPath: /usr/local/airflow/.local
  extraVolumes:
    - name: pip-cache
      emptyDir: {}
  extraVolumeMounts:
    - name: pip-cache
      mountPath: /usr/local/airflow/.local

worker:
  initContainers:
    - name: install-python-packages
      image: apache/airflow:3.1.7-python3.11
      command: ["/bin/bash", "-c"]
      args:
        - |
          pip install --no-cache-dir confluent-kafka==2.5.0 &&
          chown -R airflow:0 /usr/local/airflow/.local
      volumeMounts:
        - name: pip-cache
          mountPath: /usr/local/airflow/.local
  extraVolumes:
    - name: pip-cache
      emptyDir: {}
  extraVolumeMounts:
    - name: pip-cache
      mountPath: /usr/local/airflow/.local
